djangoTest/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

from djangoTest import settings

urlpatterns = [
    path('', include('ec.urls', namespace='ec')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

ec/urls.py
from django.urls import path

from ec import views

app_name = 'ec'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('index/', views.item_landing, name='index'),
    path('register/', views.register, name='register'),
    path('favorite/register', views.register_favorite, name='fav_register'),
    path('favorite/unregister', views.unregister_favorite, name='fav_unregister'),
]

ec/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


class Item(models.Model):
    title = models.CharField(max_length=255)
    price = models.IntegerField()
    created_at = models.DateTimeField(default=timezone.now)
    favorites = models.ManyToManyField(
        get_user_model(),
        through='Favorite'
    )


class Favorite(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

ec/forms.py
from django import forms


class SearchForm(forms.Form):
    item_name = forms.CharField(label='商品名', max_length=255, required=False,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))


class RegisterForm(forms.Form):
    title = forms.CharField(label='商品名', max_length=255,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    price = forms.IntegerField(label='商品名', min_value=0,
                               widget=forms.NumberInput(attrs={'class': 'form-control'}))

ec/views.py
import json
import logging

import django
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from ec import services
from ec.forms import SearchForm, RegisterForm

logger = logging.getLogger(__name__)


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            django.contrib.auth.login(request, user)
            return redirect('ec:index')
        return render(request, 'ec/login.html')
    else:
        return render(request, 'ec/login.html')


def logout(request):
    logout(request)
    return redirect('ec:login')


@login_required
def item_landing(request):
    if request.method == 'POST':
        logger.debug(request.POST)
        request.session['item_name'] = request.POST.get('item_name')
        return redirect('ec:index')
    else:
        if request.session.get('item_name'):
            form = SearchForm(initial={'item_name': request.session['item_name']})
        else:
            form = SearchForm()
        items = services.find_item(request.user.id, request.session.get('item_name'))
        registerForm = RegisterForm()
        return render(request, 'ec/index.html',
                      {'form': form, 'registerForm': registerForm, 'items': json.dumps(items)})


@login_required
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        services.create_item(form.title, int(form.price))
        return redirect('ec:index')


@login_required
@transaction.atomic
def register_favorite(request):
    """
    お気に入り登録.

    POST された ID 要素を ログインユーザーと紐付け、お気に入り登録済みとする。
    :param request:
    :return: 検索結果ページへのリダイレクト
    """
    if request.POST.get('id') is None:
        return redirect('ec:index')
    item_ids = request.POST.getlist('id')
    services.create_favorite_relation(request.user.id, item_ids)
    return redirect('ec:index')


@login_required
@transaction.atomic
def unregister_favorite(request):
    """
    お気に入り削除.

    POST された ID 要素を ログインユーザーと紐付け、お気に入り登録を外す。
    :param request:
    :return: 検索結果ページへのリダイレクト
    """
    if request.POST.get('id') is None:
        return redirect('ec:index')
    item_ids = request.POST.getlist('id')
    services.remove_favorite_relation(request.user.id, item_ids)
    return redirect('ec:index')

ec/templates/ec/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.20.0/dist/bootstrap-table.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'ec/common.css' %}">
    <title>Login</title>
{#    <style>#}
{#        .tab-content {#}
{#            width: 40%;#}
{#        }#}
{#    </style>#}
</head>
<body>
<header>
    <nav class="navbar navbar-light bg-light mb-2">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="{% static 'ec/mickey_silhouette.svg' %}" alt="" width="30" height="24"
                     class="d-inline-block align-text-top">
                テスト
            </a>
        </div>
    </nav>
</header>
<main>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="d-flex align-items-start">
                    <div
                            class="nav flex-column nav-pills me-3"
                            id="v-pills-tab"
                            role="tablist"
                            aria-orientation="vertical">
                        <button
                                class="nav-link active"
                                id="v-pills-home-tab"
                                data-bs-toggle="pill"
                                data-bs-target="#v-pills-home"
                                type="button"
                                role="tab"
                                aria-controls="v-pills-home"
                                aria-selected="true">
                            検索
                        </button>
                        <button
                                class="nav-link"
                                id="v-pills-profile-tab"
                                data-bs-toggle="pill"
                                data-bs-target="#v-pills-profile"
                                type="button"
                                role="tab"
                                aria-controls="v-pills-profile"
                                aria-selected="false">
                            お気に入り
                        </button>
                        <button
                                class="nav-link"
                                id="v-pills-settings-tab"
                                data-bs-toggle="pill"
                                data-bs-target="#v-pills-settings"
                                type="button"
                                role="tab"
                                aria-controls="v-pills-settings"
                                aria-selected="false">
                            コメント編集
                        </button>
                        <button
                                class="nav-link"
                                id="v-pills-register-tab"
                                data-bs-toggle="pill"
                                data-bs-target="#v-pills-register"
                                type="button"
                                role="tab"
                                aria-controls="v-pills-register"
                                aria-selected="false">
                            商品登録
                        </button>
                    </div>
                    <div class="tab-content flex-fill" id="v-pills-tabContent">
                        <div class="tab-pane fade show active"
                             id="v-pills-home"
                             role="tabpanel"
                             aria-labelledby="v-pills-home-tab">
                            <form method="post" action="{% url 'ec:index' %}">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-6">
                                        <div class="mb-3 row">
                                            <label for="{{ form.item_name.id_for_label }}"
                                                   class="col-sm-2 col-form-label">商品名</label>
                                            <div class="col-sm-10">
                                                {{ form.item_name }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 align-self-end" style="text-align: right">
                                        <button type="submit" class="btn btn-primary">検索</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane fade"
                             id="v-pills-profile"
                             role="tabpanel"
                             aria-labelledby="v-pills-profile-tab">
                            <h4>お気に入り💕</h4>
                            <div class="row mb-2">
                                <div class="col-6">
                                    <form id="registerFavForm" method="post" action="{% url 'ec:fav_register' %}">
                                        {% csrf_token %}
                                        <button id="registerFav" class="btn btn-primary">お気に入り登録</button>
                                    </form>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <form id="unregisterFavForm" method="post" action="{% url 'ec:fav_unregister' %}">
                                        {% csrf_token %}
                                        <button id="registerFav" class="btn btn-primary">お気に入り解除</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade"
                             id="v-pills-settings"
                             role="tabpanel"
                             aria-labelledby="v-pills-settings-tab">
                            コメント編集だよ✌
                        </div>
                        <div class="tab-pane fade"
                             id="v-pills-register"
                             role="tabpanel"
                             aria-labelledby="v-pills-register-tab">
                            <form method="post" action="{% url 'ec:register' %}">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-6">
                                        <div class="mb-3 row">
                                            <label for="{{ registerForm.title.id_for_label }}"
                                                   class="col-sm-2 col-form-label">商品名</label>
                                            <div class="col-sm-10">
                                                {{ registerForm.title }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <div class="mb-3 row">
                                            <label for="{{ registerForm.price.id_for_label }}"
                                                   class="col-sm-2 col-form-label">価格</label>
                                            <div class="col-sm-10">
                                                {{ registerForm.price }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 align-self-end" style="text-align: right">
                                        <button type="submit" class="btn btn-primary">登録</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <table id="itemTable"></table>
            </div>
        </div>
    </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-table@1.20.0/dist/bootstrap-table.min.js"></script>
<script>
    const $table = $('#itemTable');

    function initTable() {
        $table.bootstrapTable({
            search: true,
            pagination: true,
            pageSize: 5,
            pageList: [2, 10, 25, 50, 100, 'all'],
            columns: [{
                field: 'state',
                checkbox: true,
                align: 'center',
                valign: 'middle',
            }, {
                title: 'お気に入り',
                field: 'favorite',
                align: 'center',
                valign: 'middle',
                sortable: true,
            }, {
                title: '商品名',
                field: 'title',
                align: 'left',
                valign: 'middle',
                sortable: true,
            }, {
                title: '価格',
                field: 'price',
                align: 'right',
                valign: 'middle',
                sortable: true,
            }],
            {% autoescape off %}
                data: {{ items }}
            {% endautoescape %}
        });

        $table.on("check.bs.table", (row, $element) => {
            console.log("アイテムをチェックしました");
            console.log($element);
        });
    }

    $(function () {
        initTable();
    });

    $('form#registerFavForm').on('submit', (event) => {
        console.log("お気に入り登録ボタンをクリックした");
        let selections = $table.bootstrapTable('getSelections');
        console.log(selections);
        {# 登録済みのアイテム検知 #}
        for (let selection of selections) {
            if (selection['favorite'] === '★') {
                alert("お気に入り登録済みのアイテムが選択されています。\nお気に入り未登録のアイテムのみを選択してください。");
                return false;
            }
        }
        {# 送信データの生成 #}
        let $form = $('form#registerFavForm');
        for (let selection of selections) {
            $form.append($("<input>", {
                name: 'id',
                type: 'hidden',
                value: selection['id'],
            }));
        }
        return true;
    });

    $('form#unregisterFavForm').on('submit', (event) => {
        console.log("お気に入り登録ボタンをクリックした");
        let selections = $table.bootstrapTable('getSelections');
        console.log(selections);
        {# 登録済みのアイテム検知 #}
        for (let selection of selections) {
            if (selection['favorite'] === '☆') {
                alert("お気に入り未登録のアイテムが選択されています。\nお気に入り登録済みのアイテムのみを選択してください。");
                return false;
            }
        }
        {# 送信データの生成 #}
        let $form = $('form#unregisterFavForm');
        for (let selection of selections) {
            $form.append($("<input>", {
                name: 'id',
                type: 'hidden',
                value: selection['id'],
            }));
        }
        return true;
    });
</script>
</body>
</html>

ec/templates/ec/login.html
<!DOCTYPE html>
<html lang="ja">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'ec/signin.css' %}">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <title>Login</title>
</head>
<body>
<header>
    {#    <nav class="navbar navbar-light bg-light">#}
    {#        <div class="container-fluid">#}
    {#            <a class="navbar-brand" href="#">Navbar</a>#}
    {#        </div>#}
    {#    </nav>#}
</header>
<main class="form-signin">
        <form method="post">
            {% csrf_token %}
            <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

            <div class="form-floating">
                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="admin">
                <label for="floatingInput">Username</label>
            </div>
            <div class="form-floating">
                <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>

            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
        </form>
    </main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>